<a href="https://colab.research.google.com/github/VHDRKL/1031/blob/main/ch04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.utils import to_categorical
sample = np.array([
          [[0],[1]],
          [[1],[1]],
          [[1],[2]],
          [[2],[0]]
])
sample.shape
label = np.array([1,2,0,1])
sample.shape # (4,2,1)  4筆資料, 每兩筆時序當輸入

label = to_categorical(label)
label 

sample = to_categorical(sample)
sample.shape #(4,2,3) 4筆資料, 每兩個時序當輸入

model=Sequential()
f1=tf.keras.layers.SimpleRNN(units=3,
             dropout=0.0,
             activation='softmax',
             input_shape=(2,3),
             recurrent_dropout=0.0,    
             go_backwards=False)
model.add(f1)
model.summary() #m*d+d + d*d m=3,d=3 total=21
#Call arguments:
# input: A 3D tensor,with shape ([batch, timesteps, feature])
model.compile(optimizer=tf.keras.optimizers.RMSprop(),
        loss=tf.keras.losses.CategoricalCrossentropy(),
        metrics=['acc'])

model.fit(x=sample, y=label, epochs=500)


In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.utils import to_categorical
sample = np.array([
          [[0],[1]],
          [[1],[1]],
          [[1],[2]],
          [[2],[0]]
])
sample.shape
label = np.array([1,2,0,1])
sample.shape # (4,2,1)  4筆資料, 每兩筆時序當輸入

label = to_categorical(label)
label 

sample = to_categorical(sample)
sample.shape #(4,2,3) 4筆資料, 每兩個時序當輸入

model=Sequential()
f1=tf.keras.layers.SimpleRNN(units=10,
             dropout=0.0,
             activation='relu',
             input_shape=(2,3),
             recurrent_dropout=0.0,    
             go_backwards=False)
model.add(f1)
f2=tf.keras.layers.Dense(3, activation='softmax')
model.add(f2)
model.summary() #m*d+d + d*d m=3,d=3 total=21
#Call arguments:
# input: A 3D tensor,with shape ([batch, timesteps, feature])
model.compile(optimizer=tf.keras.optimizers.RMSprop(),
        loss=tf.keras.losses.CategoricalCrossentropy(),
        metrics=['acc'])

model.fit(x=sample, y=label, epochs=500)


In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.utils import to_categorical
from tensorflow.preprocessing.sequence import TimeseriesGenerator

dinner=[0,1,1,2,0,1,1,2]
dinner=to_categorical(dinner)
TimeseriesGenerator(dinner, dinner, 
          length=3,
          sampling_rate=1,
          stride=1,
          batch_size=2)
data_gen[0]
sample = np.array([
          [[0],[1]],
          [[1],[1]],
          [[1],[2]],
          [[2],[0]]
])
sample.shape
label = np.array([1,2,0,1])
sample.shape # (4,2,1)  4筆資料, 每兩筆時序當輸入

label = to_categorical(label)
label 

sample = to_categorical(sample)
sample.shape #(4,2,3) 4筆資料, 每兩個時序當輸入

model=Sequential()
f1=tf.keras.layers.SimpleRNN(units=10,
             dropout=0.0,
             activation='relu',
             input_shape=(2,3),
             recurrent_dropout=0.0,    
             go_backwards=False)
model.add(f1)
f2=tf.keras.layers.Dense(3, activation='softmax')
model.add(f2)
model.summary() #m*d+d + d*d m=3,d=3 total=21
#Call arguments:
# input: A 3D tensor,with shape ([batch, timesteps, feature])
model.compile(optimizer=tf.keras.optimizers.RMSprop(),
        loss=tf.keras.losses.CategoricalCrossentropy(),
        metrics=['acc'])

model.fit(x=sample, y=label, epochs=500)


In [32]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.sequence import TimeseriesGenerator

dinner=[0,1,1,2,0,1,1,2]
#dinner=to_categorical(dinner)
data_gen= TimeseriesGenerator(dinner, dinner, 
          length=3,
          sampling_rate=1,
          stride=1,
          batch_size=2)
print(data_gen[0])
print(data_gen[1])
print(data_gen[2])


(array([[0, 1, 1],
       [1, 1, 2]]), array([2, 0]))
(array([[1, 2, 0],
       [2, 0, 1]]), array([1, 1]))
(array([[0, 1, 1]]), array([2]))


In [33]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.sequence import TimeseriesGenerator

dinner=[0,1,1,2,0,1,1,2]
#dinner=to_categorical(dinner)
data_gen= TimeseriesGenerator(dinner, dinner, 
          length=3,
          sampling_rate=1,
          stride=1,
          batch_size=3)
print(data_gen[0])
print(data_gen[1])
print(data_gen[2])


(array([[0, 1, 1],
       [1, 1, 2],
       [1, 2, 0]]), array([2, 0, 1]))
(array([[2, 0, 1],
       [0, 1, 1]]), array([1, 2]))
(array([], dtype=float64), array([], dtype=float64))
