<a href="https://colab.research.google.com/github/VHDRKL/1031/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import tensorflow as tf
import numpy as np
a=tf.constant(1)
v=tf.constant([1,2,3,4,5,6])
c=np.array([[1, 2, 3],[4, 5, 6]])
c=tf.constant(c)
d=tf.constant(0, shape=(2,3))
e=tf.constant(1, dtype=tf.double)
tf.convert_to_tensor(np.ones([2,3]))
tf.convert_to_tensor(([2,3],[3,4]))
tf.zeros([2,3,3])
tf.ones([2,3])
b=[[1,2,3],[4,5,6]]
tf.zeros_like(b)
tf.ones_like(b)
tf.fill([2,3],-2,1)
tf.random.normal([2,3], mean=3, stddev=0.1)
tf.random.truncated_normal([2,3], mean=1, stddev=0.5)
tf.random.uniform([2,3], minval=1, maxval=2 )
tf.convert_to_tensor(np.arange(80).reshape(2,2,4,5))
a=tf.convert_to_tensor(np.arange(40).reshape(2,4,5))
a=tf.convert_to_tensor(np.arange(80).reshape(2,2,4,5))
#a[0][1][2][3] = a[0,1,2,3]
a[0:1,0:1,0:4,0:5]
a[1:2,...,0:5]
b=np.arange(20).reshape(4,5)

tf.gather(b, axis=1, indices=[0,2,3])
tf.gather_nd(b,[[0,2],[3,3]])

a=tf.random.uniform([3,3], minval=-10, maxval=10, dtype=tf.int32)
mask=a<0  #tf.boolean_mask(a,mask) trun false
m_index=tf.where(mask)
print(a, tf.gather_nd(a, m_index))
condition=tf.random_uniform([3,3], minval=0, maxval=2, dtype=tf.int32)
condition, tf.cast(condition, tf.bool)

a=range(1,10)
a=tf.reshape(a, [3,3])
b=tf.range(-9,0)
b=tf.reshape(b, [3,3])
condition, tf.cast(condition, tf.bool)
c=tf.where(condition. a, b ) #Truer取a的值, False取b的值


tf.Tensor(
[[ 0 -6 -9]
 [ 0 -3  5]
 [ 5  0 -1]], shape=(3, 3), dtype=int32) tf.Tensor([-6 -9 -3 -1], shape=(4,), dtype=int32)


AttributeError: ignored